version: "3.9"
services:
  streamlit:
    build: ./streamlit
    networks:
      shared-nw:
    volumes:
      - ./streamlit:/streamlit
    ports:
      - 8501:8501
    command: streamlit run ./streamlit/app.py
  nginx:
    build: ./nginx
    networks:
      shared-nw:
    ports:
      - 80:80
networks:
  shared-nw:
    driver: bridge